const SERVER_ERROR = 'server_error'
const TAG_INVALID = 'invalid'
const TAG_STATUS_REGISTERED = 'registered'
const TAG_STATUS_UNREGISTERED = 'unregistered'
const TAG_FORMAT_REGEX = /\d{4}-\d{4}/

export { SERVER_ERROR, TAG_INVALID, TAG_STATUS_REGISTERED, TAG_STATUS_UNREGISTERED, TAG_FORMAT_REGEX }
