const SERVER_ERROR = 'server_error'
const TAG_INVALID = 'invalid'
const TAG_STATUS_REGISTERED = 'registered'
const TAG_STATUS_UNREGISTERED = 'unregistered'

export { SERVER_ERROR, TAG_INVALID, TAG_STATUS_REGISTERED, TAG_STATUS_UNREGISTERED }
