const SERVER_ERROR = 'server_error'
const TAG_INVALID = 'invalid'
const TAG_STATUS_REGISTERED = 'registered'
const TAG_STATUS_UNREGISTERED = 'unregistered'
const TAG_FORMAT_REGEX = /\d{4}-\d{4}/
const ADMIN_EMAIL = 'admin@loca8.me'

const MESSAGE_TYPE_ACTIVATION = 'ACTIVATION'
const MESSAGE_TYPE_RETURN = 'RETURN'
const MESSAGE_CHANNEL_SMS = 'SMS'
const MESSAGE_CHANNEL_EMAIL = 'EMAIL'
const MESSAGE_CHANNEL_WHATSAPP = 'WHATSAPP'

const MSGBIRD_SMS_CHANNEL = 'f4cce3001e3a442f82af178ee944a24d'
const MSGBIRD_SMS_SENDER = '12053952552' //  US Phone number purchased

export {
  SERVER_ERROR,
  TAG_INVALID,
  TAG_STATUS_REGISTERED,
  TAG_STATUS_UNREGISTERED,
  TAG_FORMAT_REGEX,
  ADMIN_EMAIL,
  MESSAGE_TYPE_ACTIVATION,
  MESSAGE_TYPE_RETURN,
  MESSAGE_CHANNEL_SMS,
  MESSAGE_CHANNEL_EMAIL,
  MESSAGE_CHANNEL_WHATSAPP,
  MSGBIRD_SMS_CHANNEL,
  MSGBIRD_SMS_SENDER,
}
